This notebook will pull from the FPL API the weekly results for each player and stack all the results into a single df

Update weekly

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
top500 = pd.read_csv('top500.csv', index_col='id_')
teams = pd.read_csv('teams', index_col=0)

In [3]:
histories = {}

for id_ in top500.index:
    url = 'https://fantasy.premierleague.com/api/element-summary/' + str(id_) + '/'
    r = requests.get(url)
    player_data = r.json()
    player_history = player_data['history']
    
    histories[id_] = player_history

In [4]:
salah = pd.DataFrame(histories[191])

In [5]:
salah['total_points']

0     12
1      3
2     15
3      6
4      9
5      5
6      3
7      2
8      0
9      7
10     2
11     8
12     0
13     3
14     0
15    13
16    16
17     3
18     3
19    10
20     6
21     7
22     2
23    14
24    16
25     3
26     7
27     2
Name: total_points, dtype: int64

In [6]:
history_dfs = {}

for key in histories:
    df = pd.DataFrame(histories[key])
    df['id_'] = key
    df['web_name'] = top500.loc[key]['web_name']
    df['gameweek'] = [i for i in range(1, df.shape[0] + 1)]
    df['team'] = top500['team'].loc[key]
    df['sum_minutes'] = [sum(df['minutes'].iloc[:i+1]) for i in range(len(df.index))]
    df['sum_points'] = [sum(df['total_points'].iloc[:i+1]) for i in range(len(df.index))]
    df['next_week_points'] = df['total_points'].drop(0).append(pd.Series(0)).reset_index(drop=True)
    
    history_dfs[key] = df

In [7]:
pd.set_option('display.max_columns', 100)
history_dfs[191]

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,value,transfers_balance,selected,transfers_in,transfers_out,id_,web_name,gameweek,team,sum_minutes,sum_points,next_week_points
0,191,1,14,12,True,2019-08-09T19:00:00Z,4,1,1,90,1,1,0,1,0,0,0,0,0,0,2,40,54.8,39.7,39.0,13.4,125,0,2375465,0,0,191,Salah,1,10,90,12,3
1,191,19,16,3,False,2019-08-17T14:00:00Z,1,2,2,78,0,0,1,0,0,0,0,0,0,0,0,0,2.4,11.8,29.0,4.3,125,114282,2778082,156910,42628,191,Salah,2,10,168,15,15
2,191,24,1,15,True,2019-08-24T16:30:00Z,3,1,3,90,2,0,0,1,0,0,0,0,0,0,3,43,71.2,16.6,67.0,15.5,125,-351541,2444065,47097,398638,191,Salah,3,10,258,30,6
3,191,32,5,6,False,2019-08-31T16:30:00Z,0,3,4,90,0,1,1,0,0,0,0,0,0,0,0,15,27.0,38.4,58.0,12.3,125,243530,2810462,291554,48024,191,Salah,4,10,348,36,9
4,191,44,13,9,True,2019-09-14T11:30:00Z,3,1,5,90,1,0,0,1,0,0,0,0,0,0,2,34,44.6,41.8,73.0,15.9,125,31898,2874525,124574,92676,191,Salah,5,10,438,45,5
5,191,53,6,5,False,2019-09-22T15:30:00Z,1,2,6,90,0,1,0,1,0,0,0,0,0,0,0,11,14.8,15.3,36.0,6.6,125,-80384,2804643,49872,130256,191,Salah,6,10,528,50,3
6,191,68,15,3,False,2019-09-28T11:30:00Z,0,1,7,90,0,0,1,0,0,0,0,0,0,0,0,2,7.6,13.3,68.0,8.9,125,48879,2889458,123616,74737,191,Salah,7,10,618,53,2
7,191,74,9,2,True,2019-10-05T14:00:00Z,2,1,8,90,0,0,0,1,0,0,0,0,0,0,0,5,18.2,37.7,94.0,15.0,125,-92287,2797360,34441,126728,191,Salah,8,10,708,55,0
8,191,87,12,0,False,2019-10-20T15:30:00Z,1,1,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,124,-601424,2186184,13726,615150,191,Salah,9,10,708,55,7
9,191,94,17,7,True,2019-10-27T16:30:00Z,2,1,10,84,1,0,0,1,0,0,0,0,0,0,0,25,45.0,15.3,93.0,15.3,124,-114968,2096834,23153,138121,191,Salah,10,10,792,62,2
10,191,102,2,2,False,2019-11-02T15:00:00Z,1,2,11,64,0,0,0,1,0,0,0,0,0,0,0,4,0.0,1.2,35.0,3.5,124,-101601,2001830,29418,131019,191,Salah,11,10,856,64,8
11,191,114,11,8,True,2019-11-10T16:30:00Z,3,1,12,86,1,0,0,1,0,0,0,0,0,0,1,25,45.2,3.3,48.0,9.7,123,-110997,1894445,26242,137239,191,Salah,12,10,942,72,0
12,191,125,7,0,False,2019-11-23T15:00:00Z,1,2,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,123,-233449,1659338,36039,269488,191,Salah,13,10,942,72,3
13,191,134,4,3,True,2019-11-30T15:00:00Z,2,1,14,68,0,0,1,0,0,0,0,0,0,0,0,6,0.4,12.7,30.0,4.3,122,-43760,1632180,37183,80943,191,Salah,14,10,1010,75,0
14,191,149,8,0,True,2019-12-04T20:15:00Z,5,2,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,122,-49660,1585242,11978,61638,191,Salah,15,10,1010,75,13
15,191,152,3,13,False,2019-12-07T15:00:00Z,0,3,16,90,1,1,1,0,0,0,0,0,0,0,2,34,63.2,51.5,91.0,20.6,122,-79042,1511749,42208,121250,191,Salah,16,10,1100,88,16
16,191,166,18,16,True,2019-12-14T12:30:00Z,2,0,17,90,2,0,1,0,0,0,0,0,0,0,3,38,69.8,3.9,125.0,19.9,122,58171,1582495,84297,26126,191,Salah,17,10,1190,104,3
17,191,186,9,3,False,2019-12-26T20:00:00Z,0,4,19,69,0,0,1,0,0,0,0,0,0,0,0,5,0.0,15.9,25.0,4.0,122,233179,1722996,244647,11468,191,Salah,18,10,1259,107,3
18,191,194,20,3,True,2019-12-29T16:30:00Z,1,0,20,90,0,0,1,0,0,0,0,0,0,0,0,0,12.6,38.5,31.0,8.2,123,63148,1787526,89337,26189,191,Salah,19,10,1349,110,10
19,191,204,15,10,True,2020-01-02T20:00:00Z,2,0,21,90,1,0,1,0,0,0,0,0,0,0,2,32,46.8,40.2,90.0,17.7,123,-15901,1773138,53382,69283,191,Salah,20,10,1439,120,6
20,191,219,17,6,False,2020-01-11T17:30:00Z,0,1,22,90,0,1,1,0,0,0,0,0,0,0,0,25,22.6,40.2,30.0,9.3,123,57249,1838831,97161,39912,191,Salah,21,10,1529,126,7
21,191,224,12,7,True,2020-01-19T16:30:00Z,2,0,23,90,1,0,1,0,0,0,0,1,0,0,0,23,44.4,32.7,55.0,13.2,123,48254,1891529,93684,45430,191,Salah,22,10,1619,133,2
22,191,237,20,2,False,2020-01-23T20:00:00Z,1,2,24,84,0,0,0,1,0,0,0,0,0,0,0,12,10.8,18.5,86.0,11.5,124,283380,2229655,299473,16093,191,Salah,23,10,1703,135,14
23,191,180,19,14,False,2020-01-29T19:45:00Z,0,2,24,90,1,1,1,0,0,0,0,0,0,0,3,44,50.0,28.8,48.0,12.7,124,283380,2229655,299473,16093,191,Salah,24,10,1793,149,16
24,191,245,16,16,True,2020-02-01T15:00:00Z,4,0,25,90,2,0,1,0,0,0,0,0,0,0,3,48,80.6,32.5,100.0,21.3,126,803943,3010184,822531,18588,191,Salah,25,10,1883,165,3
25,191,257,14,3,False,2020-02-15T17:30:00Z,0,1,26,90,0,0,1,0,0,0,0,0,0,0,0,3,7.2,24.7,81.0,11.3,127,336144,3339544,347516,11372,191,Salah,26,10,1973,168,7
26,191,266,19,7,True,2020-02-24T20:00:00Z,3,2,27,90,1,0,0,2,0,0,0,0,0,0,0,27,47.2,15.3,112.0,17.5,128,-6217,3334641,76200,82417,191,Salah,27,10,2063,175,2
27,191,279,18,2,False,2020-02-29T17:30:00Z,3,0,28,90,0,0,0,3,0,0,0,0,0,0,0,5,0.0,3.3,30.0,3.3,128,23476,3382869,57735,34259,191,Salah,28,10,2153,177,0

In [8]:
top500histories = pd.concat(history_dfs.values(), ignore_index=True)
top500histories.shape

(11997, 38)

In [9]:
top500histories.to_csv('pre_top500histories.csv')

In [10]:
top500histories.columns

Index(['element', 'fixture', 'opponent_team', 'total_points', 'was_home',
       'kickoff_time', 'team_h_score', 'team_a_score', 'round', 'minutes',
       'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'value', 'transfers_balance', 'selected',
       'transfers_in', 'transfers_out', 'id_', 'web_name', 'gameweek', 'team',
       'sum_minutes', 'sum_points', 'next_week_points'],
      dtype='object')

In [11]:
top500histories.shape[0]

11997